### ISSUE TITLE
Change "Institutional spending" caption

### ISSUE THREAD

**Issue by cbroschinski** [subugoe/hybrid_oa_dashboard#1]
Minor issue: Maybe you should make more clear that the lower right plot only relates to the yellow OpenAPC share of the current selection, not the whole set of articles - one might draw some very wrong conclusions here.

Otherwise, a great project!

**Comment by njahn82** [comment]
Great thanks. Agreed, should make it more clear that all plots are relative to the selection. Maybe a more prominent link to this plot could help:
https://github.com/subugoe/hybrid_oa_dashboard/blob/master/img/licensing_coverage.png
