### ISSUE TITLE
Journal dropdown list incomplete 

### ISSUE THREAD

**Issue by cbroschinski** [subugoe/hybrid_oa_dashboard#5]
There's an issue with the journal dropdown selection: The list gets cut off at 1000 entries (Happens when publisher is set to "all" or "Springer Nature").
To save you the first 100 meters of the rabbit hole: The reason is that [selectInput](http://shiny.rstudio.com/reference/shiny/latest/selectInput.html) utilizes a JS library called [selectize.js](https://github.com/selectize/selectize.js) in its default work mode and that library limits the select box options to 1000 [per default](https://github.com/selectize/selectize.js/blob/master/docs/usage.md) ("maxOptions").

**Comment by njahn82** [comment]
Great, I was not aware of this limit because I always used the search functionality to find a particular journal.

Simply passed a limit of 5000 to function and deployed these changes to shinyapps.

Thanks!

**Comment by maxheld83** [comment]
closed in https://github.com/subugoe/hybrid_oa_dashboard/commit/0396fbd4a1a0ca54d8deb2c28e176e2535924509
