### ISSUE TITLE
add orcid for henrieke

### ISSUE THREAD

**Issue by maxheld83** [subugoe/hybrid_oa_dashboard#65]
@Henrieke72 if you have the time, could you paste your ORCID in here as a comment? 

I searched online but couldn't find one for you.

I can then add it to the package so you're properly credited 😄. Not urgent or anything.

**Comment by maxheld83** [comment]
if you have the time not urgent or anything @Henrieke72

**Comment by Henrieke72** [comment]
My ORCID: https://orcid.org/0000-0003-3313-7364
