### ISSUE TITLE
can u guide me to create the same kind of multiple reports to my proje

### ISSUE THREAD

**Issue by saisaranv** [subugoe/hybrid_oa_dashboard#9]
Hi ,

i am trying to create the multiple dashboards but not able to understand how i need to populate my data which is in rscript , also how to include selection buttons as per my tables,
i have seen many examples but getting confusion.
please help me to create.

**Comment by njahn82** [comment]
I found this overview article very helpful when starting with the dashboard:
https://rmarkdown.rstudio.com/flexdashboard/shiny.html

There is also a Data Camp tutorial about creating dashboards with shiny
https://www.datacamp.com/courses/building-dashboards-with-shinydashboard

Hope, it helps!

**Comment by saisaranv** [comment]
Thank u so much for the quick response.

**Comment by saisaranv** [comment]
HI can u help me with below one? 

I have a small business and i have 16 paid and free plans combinations.
id(PK)/name/dob/account created_at/country/score/action1....action120/ paid_free/plan

score: to sort the customers we are assigning some score based on the page he entered in site.
action1- login in to account
action2- cliks on add
action3- used our tool noraml pages of publishing
action4- used high priority page 
..
paid_free-yes or no
plan--01/02/03/04/...16 plans

like wise based on the page visit/page publish weightage is assigned. how many times he enters in the page or he clicks on add count will be increased.
so finally we are having the total score for each user id.

my intention is to figure out which action is having most priority and what is the probablity of a customer will turn to paid so that i can contact priority customers
.
i have tried with linear regression and logistic regression,my code:

r1 <- randomForest(paid_free ~.,data=data1)
r2 <- gbm(paid_free~.,data=data1)
r3 <- rpart(paid_free~.,data=data1)
r4 <- bayesglm(paid_free~.,data=data1, family=binomial)

yy1 <- predict(r1, data.frame(x=xx))
yy2 <- predict(r2, data.frame(x=xx))
yy3 <- predict(r3, data.frame(x=data1))
yy4 <- predict(r4, data.frame(x=data1), type="response")

but getting different results ,errors for random forest as "acion1" not found.
finally i have tried random forest which is quietly opposite of results compared to logistic regression (code :test1<- glm(paid_free~.,data=data1,family="binomial")

1.so which algorithms helps me most? 
2.which method makes me more usefull? 
3.can i build automatic dashboards like if any customer registers and after 15days i need to know the probability as he will convert or not?

**Comment by saisaranv** [comment]
HI can u help me with below one? 

I have a small business and i have 16 paid and free plans combinations.
id(PK)/name/dob/account created_at/country/score/action1....action120/ paid_free/plan

score: to sort the customers we are assigning some score based on the page he entered in site.
action1- login in to account
action2- cliks on add
action3- used our tool noraml pages of publishing
action4- used high priority page 
..
paid_free-yes or no
plan--01/02/03/04/...16 plans

like wise based on the page visit/page publish weightage is assigned. how many times he enters in the page or he clicks on add count will be increased.
so finally we are having the total score for each user id.

my intention is to figure out which action is having most priority and what is the probablity of a customer will turn to paid so that i can contact priority customers
.
i have tried with linear regression and logistic regression,my code:

r1 <- randomForest(paid_free ~.,data=data1)
r2 <- gbm(paid_free~.,data=data1)
r3 <- rpart(paid_free~.,data=data1)
r4 <- bayesglm(paid_free~.,data=data1, family=binomial)

yy1 <- predict(r1, data.frame(x=xx))
yy2 <- predict(r2, data.frame(x=xx))
yy3 <- predict(r3, data.frame(x=data1))
yy4 <- predict(r4, data.frame(x=data1), type="response")

but getting different results ,errors for random forest as "acion1" not found.
finally i have tried random forest which is quietly opposite of results compared to logistic regression (code :test1<- glm(paid_free~.,data=data1,family="binomial")

1.so which algorithms helps me most? 
2.which method makes me more usefull? 
3.can i build automatic dashboards like if any customer registers and after 15days i need to know the probability as he will convert or not?

**Comment by njahn82** [comment]
I will close this ticket because it does not relate to the work done in this repo.
